### PR TITLE
Add SBT Support

### PR DESCRIPTION
**Pull request by joeywatts**
#2 @ewmson @saurabhc123 

I provided simple documentation on SBT usage in the "UsingSBT.md" markdown file. I was able to run the Prediction Engine using this setup. Please let me know if you have any issues.

### CODE REVIEW

**Comment by joeywatts** [comment]
Hold off on reviewing this. I have to change something.

**Comment by joeywatts** [comment]
Ok, now it's ready.

**Comment by ewmson** [comment]
When I built it I had some errors with the test classes. They were not included in the sbt file.

Was there a specific version you were targeting?

**Comment by joeywatts** [comment]
Ah, my bad. This is an issue with the pricing data project that hasn't
actually been implemented yet.

**Comment by ewmson** [comment]
@joeywatts Please verify the latest change I made and we can commit this.

**Comment by ewmson** [comment]
Ah, I see that you have completely removed that testing library. I will take it back off to not clutter up the build files.

**Pull request merged**
